version: '3.9'

services:
  pytorch-backend: 
    build: ./app
    ports:
      - "9001:9001"
    volumes:
    - "./models:/app/models"
    - "./config:/app/config"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]